version: '3.1'

services:

  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    volumes:
      - "./db:/var/lib/mysql"
      - "./scripts:/root/scripts"
  
  pma:
    image: phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mariadb
    ports:
      - 8000:80